### ISSUE TITLE
transform the body without interceptors

### ISSUE THREAD

**Issue by its-dibo** [gid-oss/dataui-nestjs-crud#37]
I want to transform the body before creating a resource.
I know we can use interceptors or overriding the crud methods, but creating an interceptor class for each route is overkill and harder than implementing the crud from scratch.

there is a lighter solution, a transform function that takes the body (or maybe the request) and returns the new body (or request)

```
@Crud({
  model: { ... },
  routes: {
   createOneBase: {
    // or transform(req) => newReq
     transform(body: MyEntity ) => ({ ...body, status:"ok" })
   }
}
})
```

**Comment by zaro** [comment]
Is this a feature request?

Also, this is already as you said by overriding the respective method and calling your transform and the super method with the result of the transform.
Overriding also gives you the control of how to handle errors, while with the transform example you give this is not clear at all.

Can you elaborate what exactly is your pain point with overriding crud method, because to me the transform you propose doesn't seems like improvement?

**Comment by zaro** [comment]
Yes, I get that writing interceptors is too much or such a simple functionality.
But what about overriding ?  Something like that:

```ts
@Crud({
  model: { ... }
})
@Controller('example')
export class ExampleController {
  constructor( public service: ExampleService,) {
  }

  @Override('createOneBase')
  _createOneBase(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: any,
  ): Promise<any> {
  const newBody = transform(dto);

  super.createOneBase(req, newBody)
  }

```

**Comment by zaro** [comment]
@its-dibo Is the provided answer working for you? 

I am closing the issue, please reopen it in case it is not.
